### ISSUE TITLE
[bug] Syncing without fast-sync checkpoints returns an error

### ISSUE THREAD

**Issue by who-biz** [qwertycoin-org/qwertycoin#106]
I receive the following error when attempting to sync from scratch, using the `--without-checkpoints` flag.   When were minimum fees applied? 1.0 seems awfully high.  If fees lower were allowed prior to a certain height, that needs added to tx verification it looks like. 

```
 DEBUG   transaction 0e7ea5c090b4f85ef54c6f3e17afb9b618dbb7a00cfaf8a93a39219ff045733e came in processObjects
 ERROR   [Core] Transaction fee is not enough: 0.01000000, minimum fee: 1.00000000
```

**Comment by who-biz** [comment]
As a result of this, when that flag is turned on, I am unable to sync past block 6875.

**Comment by who-biz** [comment]
See here: https://github.com/monero-project/monero/pull/5547 Looks like they're not willing to patch this one, either. So whether something is done about it.... really up to you a decision.

**Comment by who-biz** [comment]
this will not be the easiest fix, as some analytics will be needed to determine at what point https://github.com/qwertycoin-org/qwertycoin/commit/0795bd0220301fc89b5520ad7f715d09ab8013fe this change in minimum fees took effect.  It was a effectively a hardforking change, but was not treated as such. So, restrospectively, we need to figure out when the most recent transaction with a fee below this amount took place.

**Comment by nnian** [comment]
Easiest move is to change the fee back to the previous lower fee within the next PR?

**Comment by nnian** [comment]
@who-biz this should fix the `--without-checkpoints` problem. I've added the update height for the minimum fee.

**Comment by who-biz** [comment]
awesome. @nnian closing as resolved, then.
