### ISSUE TITLE
getTransactions return null

### ISSUE THREAD

**Issue by huachao0326** [qwertycoin-org/qwertycoin#109]
curl --data-binary '{"jsonrpc":"2.0","id":"curltext","method":"getTransactions","params":{"blockHash":"093cc6db4e697146725f9a6499c79b48dcfba10e529b391e7aff13bdf04db881","blockCount":1}}' -H 'content-type:text/plain;' http://127.0.0.1:8071/json_rpc
return:
{"id":"curltext","jsonrpc":"2.0","result":{"items":[]}}
wallet start by:
walletd --container-file=/var/qwc/biweitest1 --container-password=11111111 --bind-address=127.0.0.1 --bind-port=8071 --daemon-address=127.0.0.1 --daemon-port=8197 --daemon
qwertycoind start by:
qwertycoind --log-file=/var/qwc/log/qwertycoin.log --enable-blockchain-indexes --rpc-bind-ip=127.0.0.1 --rpc-bind-port=8197
walletd --version
walletd v5.1.4.3030
qwertycoind --version
Qwertycoin v5.1.4.3030 
请问这样有什么问题吗？为什么getTransactions返回null？

**Comment by nnian** [comment]
Do you have  Transactions inside your Container?

> getTransactions() method returns an array of block and transaction hashes.

Transaction consists of transfers. Transfer is an amount-address pair. There could be several transfers in a single transaction.
