### ISSUE TITLE
Contribution. Details?

### ISSUE THREAD

**Issue by GildedHonour** [qwertycoin-org/qwertycoin#110]
I've forked the project and I'm interested in contributing to it. I want to discuss that with someone. Where can I? Do you have a slack room?

**Comment by Xecute0101** [comment]
We can freely discuss any development topics here or you could reach us through telegram channel. Depending on the contribution, we can also discuss in project or team page of github.

**Comment by GildedHonour** [comment]
I'll contact you in Telegram

**Comment by GildedHonour** [comment]
I've begun setting it up.

There're 4 tasks here in the issues and that's all, correct?
Regarding writing the documentation for the wiki, what presicely should be covered?

**Comment by Xecute0101** [comment]
https://github.com/orgs/qwertycoin-org/projects

The current issues are being handled by devs. You can propose contribution on the remaining projects as well.

**Comment by Xecute0101** [comment]
@GildedHonour Please close the issue for now as discussed in our communication. Thanks.
