### ISSUE TITLE
ERROR Exception: SwappedVector::operator[] when syncing from Zero.  Occurs from v5.2.0 onward.

### ISSUE THREAD

**Issue by who-biz** [qwertycoin-org/qwertycoin#112]
The blockchain, when synced from zero, after version 5.1.4 (5.1.4 works fine) fails to initialize with: `ERROR Exception: SwappedVector::operator[] `

Moved below from speqtr's constant management PR: 

>@speqtr I know it happens on Windows 100% if bin files are not present from previous operation. blockindex and block.bin files are at 0 or 1kb and swapped vector error[] will be saved in the log file.

>It is not from this update. After 5.1.4, we started to see this problem. 5.1.4 works fine.

This was what I experienced as well, when merging the changes from master branch into the LMDB repository. I fixed the issue, by reverting to 5.1.4.

It is probably helpful to note that the error does not occur if the blockchain has already begun syncing on a prior attempt. So the error appears to only occur when syncing from 0. @Xecute0101 could you clarify the bit about 1kb?

**Comment by Xecute0101** [comment]
@who-biz daemon tries to create genesis block for some reason. I think that's where the problem comes from.

**Comment by who-biz** [comment]
That is a normal behavior, as genesis block needs added whenever blockchain is synced anew.  It is possible that the wrong genesis tx is being added, though.

**Comment by who-biz** [comment]
Starting on line 346 in `lib/CryptoNoteCore/SwappedVector.h`: 

```

    if (index >= m_offsets.size()) {
        throw std::runtime_error("SwappedVector::operator[]");
    }

    if (!m_itemsFile) {
        throw std::runtime_error("SwappedVector::operator[]");
    }
```

**Comment by who-biz** [comment]
I will check if changing line 346 to read: `if (index > m_offsets.size())` changes the behavior.  If so, its because the offset at genesisis 0, and so is the index.

**Comment by who-biz** [comment]
So modifying the `index >= m_offsets.size()` produces a segfault but the stack trace was helpful. Will post as soon as I’m back at my workstation

**Comment by Xecute0101** [comment]
Running adhoc checks on commits based on date instead of version because not all commits were reflected in version updates.

Up until June 15th, syncing without blockchain data(previous files or snapshot) works.

On July 10th, syncing without blockchain data(previous files or snapshot) fails.

Compiled them individually before testing so there is no possible conflict in terms of file structure.

Let's see who nails down the commit that caused this sync fiasco.

**Comment by Xecute0101** [comment]
![Check](https://user-images.githubusercontent.com/38364793/63080492-2e96de80-bf7c-11e9-8a69-80a22a51d8de.PNG)

Now down to 4 commits that is causing this vector issue.

**Comment by Xecute0101** [comment]
qwertycoind 0710(999a62f) syncs from scratch successfully.


[qwertycoind 0710(999a62f)-success.log](https://github.com/qwertycoin-org/qwertycoin/files/3504761/qwertycoind.0710.999a62f.-success.log)

**Comment by nnian** [comment]
I found it. It's https://github.com/qwertycoin-org/qwertycoin/commit/26807b2d4cad2671d4c96a924a93e3d5c52f22ee

if i revert this the error is gone

**Comment by nnian** [comment]
maybe it's the "set upgrade height" i will take a deeper look onto it

**Comment by nnian** [comment]
Yes, it's https://github.com/qwertycoin-org/qwertycoin/commit/7ffb667ab807095a805bbfe46c240f3934765c41

**Comment by Xecute0101** [comment]
qwertycoind 0710(43332a7)) fails to sync from scratch. It is before 7ffb667.

[qwertycoind  0710(43332a7)-fail.log](https://github.com/qwertycoin-org/qwertycoin/files/3504809/qwertycoind.0710.43332a7.-fail.log)

**Comment by nnian** [comment]
> 
> 
> qwertycoind 0710([43332a7](https://github.com/qwertycoin-org/qwertycoin/commit/43332a79cebefd77b5f7cc4af38de020680fb606))) fails to sync from scratch. It is before [7ffb667](https://github.com/qwertycoin-org/qwertycoin/commit/7ffb667ab807095a805bbfe46c240f3934765c41).
> 
> [qwertycoind 0710(43332a7)-fail.log](https://github.com/qwertycoin-org/qwertycoin/files/3504809/qwertycoind.0710.43332a7.-fail.log)

Yes, but in https://github.com/qwertycoin-org/qwertycoin/commit/43332a79cebefd77b5f7cc4af38de020680fb606 the changes were so small that it can not be the only issue. These functions are not used. Without the purpose of https://github.com/qwertycoin-org/qwertycoin/commit/7ffb667ab807095a805bbfe46c240f3934765c41

**Comment by Xecute0101** [comment]
> > qwertycoind 0710([43332a7](https://github.com/qwertycoin-org/qwertycoin/commit/43332a79cebefd77b5f7cc4af38de020680fb606))) fails to sync from scratch. It is before [7ffb667](https://github.com/qwertycoin-org/qwertycoin/commit/7ffb667ab807095a805bbfe46c240f3934765c41).
> > [qwertycoind 0710(43332a7)-fail.log](https://github.com/qwertycoin-org/qwertycoin/files/3504809/qwertycoind.0710.43332a7.-fail.log)
> 
> Yes, but in [43332a7](https://github.com/qwertycoin-org/qwertycoin/commit/43332a79cebefd77b5f7cc4af38de020680fb606) the changes were so small that it can not be the only issue. These functions are not used. Without the purpose of [7ffb667](https://github.com/qwertycoin-org/qwertycoin/commit/7ffb667ab807095a805bbfe46c240f3934765c41)

That's right. So now, we could pin down what is causing this vector issue. Hope it gets resolved soon.

**Comment by nnian** [comment]
I think i will revert the misconfigured PR / Commit now to have a 100% working repo and we will take care of these issues asap in the next days?

**Comment by Xecute0101** [comment]
@speqtr @exploshot @who-biz 

Your opinions, please?

**Comment by speqtr** [comment]
In file `lib/CryptoNoteCore/Currency.cpp` in function `bool Currency::getBlockReward(...)` first line `assert(alreadyGeneratedCoins <= m_moneySupply);` was commented out. But somehow got uncommented in one of my commits (probably accidentally instead of another line/comment).

**Comment by speqtr** [comment]
@nnian could you please pull the code form PR #114 and tests if it does fix this issue or not?

**Comment by nnian** [comment]
> 
> 
> In file `lib/CryptoNoteCore/Currency.cpp` in function `bool Currency::getBlockReward(...)` first line `assert(alreadyGeneratedCoins <= m_moneySupply);` was commented out in earlier versions. But somehow got uncommented in one of my commits (probably accidentally instead of another line/comment).

Mh, I already commented out that before but the error was still there.  i test it again

**Comment by nnian** [comment]
With
`//assert(alreadyGeneratedCoins <= m_moneySupply);`


It's still there

```
2019-Aug-15 11:17:56.493994 INFO    Mining has been stopped, 0 finished
SwappedVector cache hits: 0, misses: 0 (-nan(ind)%)
2019-Aug-15 11:17:56.499006 ERROR   Exception: SwappedVector::operator[]
```

**Comment by speqtr** [comment]
@nnian I think we can temporarly comment out the following code in `Currency::getBlockReward(...)`:
```
    if (height >= CryptoNote::parameters::UPGRADE_HEIGHT_REWARD_SCHEME && difficultyTarget() != 0) {
        // blockTarget is (Timestamp of New Block - Timestamp of Previous Block)
        consistency = blockTarget / difficultyTarget();

        // consistency range is 0..2
        consistency = std::max<double>(consistency, 0.0);
        consistency = std::min<double>(consistency, 2.0);
    }
```

**Comment by nnian** [comment]
> 
> 
> @nnian I think we can temporarly comment out the following code in `Currency::getBlockReward(...)`:
> 
> ```
>     if (height >= CryptoNote::parameters::UPGRADE_HEIGHT_REWARD_SCHEME && difficultyTarget() != 0) {
>         // blockTarget is (Timestamp of New Block - Timestamp of Previous Block)
>         consistency = blockTarget / difficultyTarget();
> 
>         // consistency range is 0..2
>         consistency = std::max<double>(consistency, 0.0);
>         consistency = std::min<double>(consistency, 2.0);
>     }
> ```

Have I already tested, error is still there :-/ now i'm reverting every single file out of your previous commits to find this error.

**Comment by speqtr** [comment]
Hmmm... this is weird, since that place looks like the only one "potentially buggy" place in those two commits (`43332a7` and `7ffb667`). And the previous commits sync without any issues.

**Comment by nnian** [comment]
The Error must between https://github.com/qwertycoin-org/qwertycoin/commit/58ad54b63122a6562f878d102a18656c87ecaa37 and https://github.com/qwertycoin-org/qwertycoin/commit/999a62f1b6dd173dbd89e6345b1be9b3fd42d31a

**Comment by nnian** [comment]
Now i'm here https://github.com/qwertycoin-org/qwertycoin/commit/58ad54b63122a6562f878d102a18656c87ecaa37

1) revert the entire commit
 if error is gone i will delete any single change and rebuild it to find the issue

**Comment by Xecute0101** [comment]
Just a note. When we find logical error(s) like this, dont we need to build a test code to prevent this from happening again?

**Comment by who-biz** [comment]
>Edit: Yes Error is gone after revert your first Commit Resubmitted changes from 3a4a3dd so the error must be in 58ad54b i guess. let's find it

My first thought is this: When initializing the indexes, the first block won’t have valid values possible for the “previous block hash” field. This may be causing the error, because the a vector won’t have any value for those fields and may be looking to a `NULL` value, or a default one.

**Comment by exploshot** [comment]
![Screenshot from 2019-08-16 08-27-41](https://user-images.githubusercontent.com/9617859/63147871-c5f14580-bfff-11e9-9f2c-3289084f1c79.png)

if i/we can find a solution for this, then we can go on :)

**Comment by Xecute0101** [comment]
> ![Screenshot from 2019-08-16 08-27-41](https://user-images.githubusercontent.com/9617859/63147871-c5f14580-bfff-11e9-9f2c-3289084f1c79.png)
> 
> if i/we can find a solution for this, then we can go on :)

Looks like conditional clause from the new block reward activation height is not working?

**Comment by Xecute0101** [comment]
Don't we have it here already?

if (height >= CryptoNote::parameters::UPGRADE_HEIGHT_REWARD_SCHEME && difficultyTarget() != 0) {

**Comment by nnian** [comment]
> 
> 
> > Edit: Yes Error is gone after revert your first Commit Resubmitted changes from [3a4a3dd](https://github.com/qwertycoin-org/qwertycoin/commit/3a4a3dd4bee0f1b0a73ec4132fcd66b74aa4d0fc) so the error must be in [58ad54b](https://github.com/qwertycoin-org/qwertycoin/commit/58ad54b63122a6562f878d102a18656c87ecaa37) i guess. let's find it
> 
> My first thought is this: When initializing the index, the first block won’t have valid values possible for the “previous block hash” field. This may be causing the error, because the vector won’t have any value for those fields and may be looking to a `NULL` value, or a default one.

That sounds believable. There can not be a previous hash before 0 Genesis

**Comment by exploshot** [comment]
> 
> 
> Don't we have it here already?
> 
> if (height >= CryptoNote::parameters::UPGRADE_HEIGHT_REWARD_SCHEME && difficultyTarget() != 0) {

yes but only in Currency.cpp, we need it on the other functions too.

**Comment by speqtr** [comment]
> yes but only in Currency.cpp, we need it on the other functions too.

I think we don't. What we need is to fix functions like `getBlockHeight` and `getBlockTimestamp ` (maybe some others) and make them safe when calling with invalid block hash/index/etc.

**Comment by who-biz** [comment]
>if i/we can find a solution for this, then we can go on :)

>We could solve this with a condition which checks the height > UPGRADE_HEIGHT_REWARD_SCHEME.
 
The reward scheme needs made active on a consensus-level point-of-agreement for nodes. While not spending a full coinbase output might not be problematic inherently, the fact that historicals are being interpreted differently, most definitely is an issue.  

After what change are you seeing those messages? @exploshot 

I think that height is the best point to evaluate this from, as reorgs would change block hash (but not height), presumably. 

@speqtr’s point is valid too, and a separate issue. That is: that functions need initialized to safe values rather than not differentiating between `null` initializers and actually valid ones. Throwing an exception is “safe” in my opinion, in contrast.

**Comment by Xecute0101** [comment]
> > if i/we can find a solution for this, then we can go on :)
> 
> > We could solve this with a condition which checks the height > UPGRADE_HEIGHT_REWARD_SCHEME.
> 
> The reward scheme needs made active on a consensus-level point-of-agreement for nodes. While not spending a full coinbase output might not be problematic inherently, the fact that historicals are being interpreted differently, most definitely is an issue (if I understand correctly).
> 
> After what change are you seeing those messages? @exploshot
> 
> I think that height is the best point to evaluate this from, as reorgs would change block hash (but not height), presumably. This is true for wallets as well.
> 
> @speqtr’s point is valid too, and a separate issue. That is: that functions need initialized to safe values rather than not differentiating between `null` initializers and actually valid ones. Throwing an exception is “safe” in my opinion, in contrast.

@exploshot told me that he set height >= 0 (instead of activation height) to produce what he attached in the image. So once, we get this working from the activation height correctly, we should be fine.

**Comment by exploshot** [comment]
After setting the files to height >= 500000
![Screenshot from 2019-08-16 16-12-58](https://user-images.githubusercontent.com/9617859/63173971-4c7a4700-c041-11e9-97e8-40396a91f58b.png)
![Screenshot from 2019-08-16 16-13-13](https://user-images.githubusercontent.com/9617859/63173973-4c7a4700-c041-11e9-9e74-b78d3ce25260.png)
![Screenshot from 2019-08-16 16-16-26](https://user-images.githubusercontent.com/9617859/63173974-4c7a4700-c041-11e9-92e1-a4edd055a071.png)

i've changed the variables from 58ad54b63122a6562f878d102a18656c87ecaa37 in Blockchain.cpp, BlockchainExplorerDataBuilder.cpp, Core.cpp, RpcServer.cpp

**Comment by nnian** [comment]
@exploshot please create a Pull Request

**Comment by who-biz** [comment]
Good work @exploshot

**Comment by exploshot** [comment]
> Good work @exploshot

thank you, i think it should work now.

**Comment by Xecute0101** [comment]
ERROR Exception: SwappedVector::operator[] no longer appears during startup so for this part, we found a workaround.

**Comment by who-biz** [comment]
@Xecute0101 closing as resolved.
