### ISSUE TITLE
exiting without message

### ISSUE THREAD

**Issue by exploshot** [qwertycoin-org/qwertycoin#117]
my node doesnt work fine since https://github.com/qwertycoin-org/qwertycoin/commit/7a07076521b295ecf639a16e3f118f7fea54089b
it exits without a message, here the log
[qwertycoind.log](https://github.com/qwertycoin-org/qwertycoin/files/3516793/qwertycoind.log)

Does someone figured out the same issue?

**Comment by nnian** [comment]
I had the same issue after https://github.com/qwertycoin-org/qwertycoin/pull/111
@speqtr did you found some possible errors within your PR?

**Comment by nnian** [comment]
Please see https://github.com/qwertycoin-org/qwertycoin/pull/118

**Comment by nnian** [comment]
Solved here https://github.com/qwertycoin-org/qwertycoin/pull/120
