### ISSUE TITLE
PoW hashes of blocks within a checkpoint range are null during sync process.

### ISSUE THREAD

**Issue by Xecute0101** [qwertycoin-org/qwertycoin#121]
- Null PoW Hash during blockchain sync
![1](https://user-images.githubusercontent.com/38364793/63482568-546c3800-c4d4-11e9-8f5b-26040530d91b.PNG)

- Proper PoW Hash during latest block height sync
![2](https://user-images.githubusercontent.com/38364793/63482573-57672880-c4d4-11e9-9544-90f22828e0eb.PNG)

What do you think is happening here?

**Comment by Xecute0101** [comment]
https://github.com/qwertycoin-org/qwertycoin/issues/106#issuecomment-513513913

**Comment by exploshot** [comment]
If the Block is in Checkpoint Zone [Checkpoints.h](https://github.com/qwertycoin-org/qwertycoin/blob/master/lib/Global/Checkpoints.h) the PoW Hash will not overwritten, so its NULL_HASH.

https://github.com/qwertycoin-org/qwertycoin/blob/master/lib/CryptoNoteCore/Blockchain.cpp#L2610

**Comment by Xecute0101** [comment]
I get that from the code perspective. But I guess what I am really asking is, is it okay to skip over this PoW check using checkpoint instead? I know that checkpoint will guide through selecting the right chain in case of fork. But the blocks inbetween the checkpoints rather seem vulnerable to attacks.

**Comment by exploshot** [comment]
For me its not neccessary to check the proof again. If someone changes eg block 10, he has to change all following too. Thats to much work in my eyes. The PoW Hash is only important to add a new block to the chain and we have a lot of checks to prevent the chain.

**Comment by who-biz** [comment]
I’m inclined to disagree with @exploshot as this has implications outside of simple hash checking.  In my issue report you can see that minimum fees were not getting caught in block validation because the entire block skipped validation. Not just the PoW hash.

**Comment by nnian** [comment]
Yes we should change the fee back to the old value with the next PR on a certain network height.

**Comment by nnian** [comment]
> 
> 
> I’m inclined to disagree with @exploshot as this has implications outside of simple hash checking. In my issue report you can see that minimum fees were not getting caught in block validation because the entire block skipped validation. Not just the PoW hash.

This https://github.com/qwertycoin-org/qwertycoin/pull/122 should fix the fee validation issue.

**Comment by who-biz** [comment]
@nnian that fee issue is resolved, but a separate issue. The problem within the `null_hash` masking is mostly one within making stuff a headache to debug.  This can be avoided by using the `--without-checkpoints` flag each time a full sync is being done, to check for errors or whatever.

Overall, not a huge issue.  Just might be risky to assume all blocks prior to most recent checkpoint don't require any validation.  This issue isn't resolved yet in BLUR either, but I think a safer behavior would be initializing the block hash to a safer value than `null`.  Either way, not something that threatens any safe operations, probably.

Apologies if that came off as more urgent than I intended.

**Comment by exploshot** [comment]
I thought the SwappedVector problem is fixed?

**Comment by who-biz** [comment]
It is! @exploshot I just meant in the past.
