### ISSUE TITLE
Block 391 has invalid miner transaction.

### ISSUE THREAD

**Issue by who-biz** [qwertycoin-org/qwertycoin#126]
I encountered this as I'm finishing up LMDB.  It appears that <a href="https://explorer.qwertycoin.org/?hash=a42ee3502cafdaeb8c38fe40769eab787f68b9b19060052f6e24f48ee26bde93#blockchain_block">Block 391 does not use the full amount of the block reward</a>.  You can see based on the prior block, as well as the next one, that the first transaction in the block should be around 351,000 QWC (reward).  However, the transaction's amount is only 173,000 or so.  I am unsure of why.  

Transaction in question: https://explorer.qwertycoin.org/?hash=f12661c4858886e1d40a158b81549e01157e18a2032671bdee765ed16fba2e88#blockchain_transaction

Corresponding error I'm getting when using LMDB for storage is as follows (this should show up when using `blockchain.bin` storage too, but it isn't for some reason):

```
 ERROR   Coinbase transaction doesn't use full amount of block reward: spent 173802.10365430, block reward is 351581.42279954
 INFO    Block a42ee3502cafdaeb8c38fe40769eab787f68b9b19060052f6e24f48ee26bde93 has invalid miner transaction
```

**Comment by who-biz** [comment]
I think @speqtr changed code recently to account for this, if I'm not mistaken.  Could one of you confirm that is the case?  If so, then the explorer daemon/code may just need updated. @Xecute0101 @nnian @exploshot

**Comment by who-biz** [comment]
It also appears that block 392's reward may be too large.

**Comment by nnian** [comment]
Block 391 had an Reward Penalty (for oversized Transactions inside) of 50.577%
In total it's 351581.422 QWC but miners Reward was 173,802 QWC

**Comment by who-biz** [comment]
Ah, okay. Then that explains it. I’ll have to figure out why my implementation is calculating that value incorrectly. Thanks @nnian. Closing
