### ISSUE TITLE
Someone tries to steal you work

### ISSUE THREAD

**Issue by luis-07** [qwertycoin-org/qwertycoin#159]
I just met this guy he’s some kind of a scammer or something like that and maybe it’s interesting for you to know that this troll stole your work. He’s trolling and just being a annoying dud I wouldn’t want someone like him having my repo in his listed but not a s a fork. Here a link to one of his repos https://github.com/minereobot1/qwerty-wallet-gui 
Maybe you are fine with it but I just wanted to let you know that this stupid troll exists

**Comment by Sw0rdf1sh1** [comment]
Thank you @luis-07 we will check it

**Comment by luis-07** [comment]
NP I glad you'll check it this guy is a big troll and I try to stop him. He portends to be a cyber security engineer and needs it for research.

**Comment by luis-07** [comment]
A question of interest does QWERTY COIN cost money?

**Comment by luis-07** [comment]
To describe my issue it's not that he's doing it the problem is that he a troll and people now think QWERTY coin is a scam

**Comment by Sw0rdf1sh1** [comment]
no, everyone can participate basically for free. You can mine it, buy it on exchanges or trade it with some users in their telegram groups.

**Comment by Sw0rdf1sh1** [comment]
Trolls cannot be avoided.
Anyone can fork public projects. Some will create it for serious development, others try the opposite

**Comment by luis-07** [comment]
Yes the MIT license allows it. I was wondering why it isn’t marked as fork
