### ISSUE TITLE
Not move at block 49899 for alternative chain, have not enough proof of work

### ISSUE THREAD

**Issue by KhmerRun** [qwertycoin-org/qwertycoin#19]
Hello,

I just test to run this qwerty today and also test a pool. I got some error and not move:

2018-Apr-12 09:58:16.649229 INFO    Block with id: 7266edca4916a26760961255f3e422f2cfcc6c507c674fcd3a428cd0aa8cc5d8
2018-Apr-12 09:58:16.649229 INFO     for alternative chain, have not enough proof of work: d3f60f08a02f53211893c89df4f8800dd3be055972ea76bf257d46ccc5760000
2018-Apr-12 09:58:16.649229 INFO     expected difficulty: 17261521
2018-Apr-12 09:58:19.668371 INFO    Block with id: 7266edca4916a26760961255f3e422f2cfcc6c507c674fcd3a428cd0aa8cc5d8
2018-Apr-12 09:58:19.668371 INFO     for alternative chain, have not enough proof of work: d3f60f08a02f53211893c89df4f8800dd3be055972ea76bf257d46ccc5760000
2018-Apr-12 09:58:19.668371 INFO     expected difficulty: 17261521
2018-Apr-12 09:58:34.421860 INFO    [195.201.96.78:49213 INC] Sync data returned unknown top block: 49899 -> 49902 [3 blocks (0 days) behind]
2018-Apr-12 09:58:34.421860 INFO    SYNCHRONIZATION started
2018-Apr-12 09:58:34.898160 INFO    [183.171.77.237:62844 INC] Sync data returned unknown top block: 49899 -> 49933 [34 blocks (0 days) behind]
2018-Apr-12 09:58:34.898160 INFO    SYNCHRONIZATION started
2018-Apr-12 09:58:37.447850 INFO    [77.55.237.152:8196 OUT] Sync data returned unknown top block: 49899 -> 49902 [3 blocks (0 days) behind]
2018-Apr-12 09:58:37.447850 INFO    SYNCHRONIZATION started
2018-Apr-12 09:58:44.965723 INFO    Block with id: 7266edca4916a26760961255f3e422f2cfcc6c507c674fcd3a428cd0aa8cc5d8
2018-Apr-12 09:58:44.965723 INFO     for alternative chain, have not enough proof of work: d3f60f08a02f53211893c89df4f8800dd3be055972ea76bf257d46ccc5760000
2018-Apr-12 09:58:44.965723 INFO     expected difficulty: 17261521
2018-Apr-12 09:58:49.276881 INFO    Block with id: a12e73ea06bd85bb0790ce2e46ff90836474023a74dbdf189b0898d8055835bc
2018-Apr-12 09:58:49.276881 INFO     for alternative chain, have not enough proof of work: 0e600c9d963f3037f44d8df84b849cd70dcf00f251ab801ef029c3d732020000
2018-Apr-12 09:58:49.276881 INFO     expected difficulty: 14070894
2018-Apr-12 09:58:52.475500 INFO    Block with id: a12e73ea06bd85bb0790ce2e46ff90836474023a74dbdf189b0898d8055835bc
2018-Apr-12 09:58:52.475500 INFO     for alternative chain, have not enough proof of work: 0e600c9d963f3037f44d8df84b849cd70dcf00f251ab801ef029c3d732020000
2018-Apr-12 09:58:52.475500 INFO     expected difficulty: 14070894
2018-Apr-12 09:58:52.975680 INFO    Block with id: 7266edca4916a26760961255f3e422f2cfcc6c507c674fcd3a428cd0aa8cc5d8
2018-Apr-12 09:58:52.975680 INFO     for alternative chain, have not enough proof of work: d3f60f08a02f53211893c89df4f8800dd3be055972ea76bf257d46ccc5760000
2018-Apr-12 09:58:52.975680 INFO     expected difficulty: 17261521
2018-Apr-12 09:59:00.392508 INFO    [91.229.219.130:50038 INC] Sync data returned unknown top block: 49899 -> 49933 [34 blocks (0 days) behind]
2018-Apr-12 09:59:00.392508 INFO    SYNCHRONIZATION started
2018-Apr-12 09:59:02.104185 INFO    Block with id: 7266edca4916a26760961255f3e422f2cfcc6c507c674fcd3a428cd0aa8cc5d8
2018-Apr-12 09:59:02.104185 INFO     for alternative chain, have not enough proof of work: d3f60f08a02f53211893c89df4f8800dd3be055972ea76bf257d46ccc5760000
2018-Apr-12 09:59:02.104185 INFO     expected difficulty: 17261521
2018-Apr-12 09:59:21.534590 INFO    Block with id: 7266edca4916a26760961255f3e422f2cfcc6c507c674fcd3a428cd0aa8cc5d8
2018-Apr-12 09:59:21.534590 INFO     for alternative chain, have not enough proof of work: d3f60f08a02f53211893c89df4f8800dd3be055972ea76bf257d46ccc5760000
2018-Apr-12 09:59:21.534590 INFO     expected difficulty: 17261521
2018-Apr-12 09:59:21.644632 INFO    [95.46.74.227:55794 INC] Sync data returned unknown top block: 49899 -> 49933 [34 blocks (0 days) behind]
2018-Apr-12 09:59:21.644632 INFO    SYNCHRONIZATION started
2018-Apr-12 09:59:29.461582 INFO    Block with id: 7266edca4916a26760961255f3e422f2cfcc6c507c674fcd3a428cd0aa8cc5d8
2018-Apr-12 09:59:29.461582 INFO     for alternative chain, have not enough proof of work: d3f60f08a02f53211893c89df4f8800dd3be055972ea76bf257d46ccc5760000
2018-Apr-12 09:59:29.461582 INFO     expected difficulty: 17261521
2018-Apr-12 09:59:33.802897 INFO    Block with id: 7266edca4916a26760961255f3e422f2cfcc6c507c674fcd3a428cd0aa8cc5d8
2018-Apr-12 09:59:33.802897 INFO     for alternative chain, have not enough proof of work: d3f60f08a02f53211893c89df4f8800dd3be055972ea76bf257d46ccc5760000
2018-Apr-12 09:59:33.802897 INFO     expected difficulty: 17261521
2018-Apr-12 09:59:37.279953 INFO    [95.46.74.227:8196 OUT] Sync data returned unknown top block: 49899 -> 49933 [34 blocks (0 days) behind]
2018-Apr-12 09:59:37.279953 INFO    SYNCHRONIZATION started
2018-Apr-12 09:59:38.841296 INFO    [39.119.94.221:13368 INC] Sync data returned unknown top block: 49899 -> 49933 [34 blocks (0 days) behind]
2018-Apr-12 09:59:38.841296 INFO    SYNCHRONIZATION started

**Comment by qwertycoin-org** [comment]
Hello please update your Daemon / Pool / Node / Wallet to the newest Version: 2.2.2
Thanks!
