### ISSUE TITLE
Running pool found same block as qwertycoin.site??

### ISSUE THREAD

**Issue by KhmerRun** [qwertycoin-org/qwertycoin#20]
Hello,

I test to run qwerty pool today. Everything seemed running well and found a couple of blocks with my hash rate ~2K/s. Then, I saw https://qwertycoin.site/ also found the same block later after my finding more than an hour.

Another funny is that, I open: http://qwcpool.partyvibe.com and found it has hash rate just only 30H/s to 40H/s but found so many blocks and paid. (Is it testnet)?

Can anybody let me know if this coin just only for testing not release yet

**Comment by KhmerRun** [comment]
Hi,

After upgrading and run the daemon with downloaded blockchain 2018-04-16

2018-Apr-16 07:30:58.355628 ERROR   [94.130.187.117:8196 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Apr-16 07:30:58.543575 ERROR   [195.201.25.118:8196 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Apr-16 07:30:58.731151 ERROR   [195.201.29.64:8196 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Apr-16 07:30:58.922952 ERROR   [78.47.85.215:8196 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Apr-16 07:30:58.923184 ERROR   Failed to connect to any of seed peers, continuing without seeds
2018-Apr-16 07:31:01.114076 ERROR   [78.47.85.215:8196 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Apr-16 07:31:01.308967 ERROR   [46.38.242.66:8196 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Apr-16 07:31:01.495805 ERROR   [78.47.87.215:8196 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Apr-16 07:31:01.682522 ERROR   [195.201.27.148:8196 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Apr-16 07:31:01.868001 ERROR   [94.16.122.128:8196 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Apr-16 07:31:02.051764 ERROR   [94.130.187.117:8196 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Apr-16 07:31:02.239011 ERROR   [195.201.25.118:8196 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Apr-16 07:31:02.426471 ERROR   [195.201.29.64:8196 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Apr-16 07:31:02.632789 ERROR   [78.47.85.215:8196 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Apr-16 07:31:02.632993 ERROR   Failed to connect to any of seed peers, continuing without seeds
2018-Apr-16 07:31:04.820359 ERROR   [195.201.27.148:8196 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Apr-16 07:31:05.006764 ERROR   [94.16.122.128:8196 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Apr-16 07:31:05.189395 ERROR   [94.130.187.117:8196 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Apr-16 07:31:05.375045 ERROR   [195.201.25.118:8196 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Apr-16 07:31:05.561861 ERROR   [195.201.29.64:8196 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Apr-16 07:31:05.752821 ERROR   [78.47.85.215:8196 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Apr-16 07:31:05.940851 ERROR   [46.38.242.66:8196 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Apr-16 07:31:06.127518 ERROR   [78.47.87.215:8196 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Apr-16 07:31:06.315429 ERROR   [195.201.27.148:8196 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Apr-16 07:31:06.315636 ERROR   Failed to connect to any of seed peers, continuing without seeds

**Comment by qwertycoin-org** [comment]
Nothing to be worry about it. These failed HANDSHAKES are Nodes who wants to connect with your Daemon trough an older Version.

**Comment by qwertycoin-org** [comment]
Make sure to run the correct Version:
 qwertycoin v2.2.2.2220 

With network Identifier: Network: bc473df6-3a7a-586f-a40a-6fc6fc60ab44

**Comment by KhmerRun** [comment]
I could not find that version. Let me try with git again from https://github.com/qwertycoin-org/qwertycoin ?

**Comment by KhmerRun** [comment]
After using new version, I got this:

2018-Apr-16 15:27:51.858145 ERROR   transaction is too big 21370, maximum allowed size is 19400
2018-Apr-16 15:27:52.047177 ERROR   transaction is too big 21489, maximum allowed size is 19400
2018-Apr-16 15:27:52.118058 ERROR   transaction is too big 22057, maximum allowed size is 19400
2018-Apr-16 15:27:52.168729 ERROR   transaction is too big 20206, maximum allowed size is 19400
2018-Apr-16 15:27:52.223067 ERROR   transaction is too big 20299, maximum allowed size is 19400
2018-Apr-16 15:27:52.280949 ERROR   transaction is too big 20902, maximum allowed size is 19400
2018-Apr-16 15:27:52.345233 ERROR   transaction is too big 21995, maximum allowed size is 19400
2018-Apr-16 15:27:52.453199 ERROR   transaction is too big 26295, maximum allowed size is 19400
2018-Apr-16 15:27:52.508936 ERROR   transaction is too big 21285, maximum allowed size is 19400
2018-Apr-16 15:27:52.644497 ERROR   transaction is too big 22585, maximum allowed size is 19400
2018-Apr-16 15:28:00.478858 ERROR   transaction is too big 21370, maximum allowed size is 19400
2018-Apr-16 15:28:00.844101 ERROR   transaction is too big 21489, maximum allowed size is 19400
2018-Apr-16 15:28:01.042765 ERROR   transaction is too big 22057, maximum allowed size is 19400
2018-Apr-16 15:28:01.201750 ERROR   transaction is too big 20206, maximum allowed size is 19400
2018-Apr-16 15:28:01.286408 ERROR   transaction is too big 20299, maximum allowed size is 19400
2018-Apr-16 15:28:01.363088 ERROR   transaction is too big 20902, maximum allowed size is 19400
2018-Apr-16 15:28:01.433987 ERROR   transaction is too big 21995, maximum allowed size is 19400
2018-Apr-16 15:28:01.541868 ERROR   transaction is too big 26295, maximum allowed size is 19400
