### ISSUE TITLE
Running pool for almost 2 days and no luck

### ISSUE THREAD

**Issue by KhmerRun** [qwertycoin-org/qwertycoin#21]
Hello, I test a small pool with average hash 1.5KH/s to 2KH/s and almost two days now and could not get any block. Is that so unlucky or anything behind the setting up of pool?

**Comment by qwertycoin-org** [comment]
Hi, i think its better ro mine in a existing Pool with this small Hashrate.

**Comment by KhmerRun** [comment]
Noted.
