### ISSUE TITLE
Transaction still unconfirmed for more than 12 hours

### ISSUE THREAD

**Issue by KhmerRun** [qwertycoin-org/qwertycoin#22]
Hello,

I am having issue with pending confirmation of transaction which listed as **Unconfirmed transaction**

Example:
http://xplorer.qwertycoin.org/?hash=caa596d282715ef620a5a1be0bacb39b5356a92cc6bd45896208e91b76900ecf#blockchain_transaction

http://xplorer.qwertycoin.org/?hash=1de2d116f31eeadb01e141175f703e3687da75528f50cddd2e630a7334357948#blockchain_transaction

locked amount: 302558.00000000 in http://qwcpool.partyvibe.com/ but some recent transaction was successful instead.

Can you let me know if it is from pool issue or my daemon or else?

**Comment by KhmerRun** [comment]
Hello,

Now when I checked with explorer again, there is no more information left of all pending transaction. They all gone blank.

**Comment by KhmerRun** [comment]
By resetting,
Before reset command:
2018-Apr-21 06:54:32.988453 INFO    available balance: 1309324.40000000, locked amount: 278288.60000000, total balance: 1587613.00000000

After reset command:
2018-Apr-21 06:55:12.505508 INFO    available balance: 1309324.40000000, locked amount: 7375.10000000, total balance: 1316699.50000000

I lost ~270k what i mined from http://qwcpool.partyvibe.com/

**Comment by qwertycoin-org** [comment]
This can happen. Please contact the pool owner they can help you.
