### ISSUE TITLE
c++: error: unrecognized command line option ‘-maes’ on ARM

### ISSUE THREAD

**Issue by pavulon18** [qwertycoin-org/qwertycoin#30]
While trying to follow the instructions for building this software, I ran into the error listed in the title.  After a little bit of research, I found the solution here.

[https://github.com/monero-project/monero/issues/954](https://github.com/monero-project/monero/issues/954)

Basically, the -maes flag is an x86 specific flag which is not used on ARM architecture.

I removed the "-maes" flag from the "CMakeLists.txt" file.  I don't know how to adjust the file to make it recognize when not to place the flag.

I am building this project now.  So far, I have gotten further in the process than I had before.

**Comment by qwertycoin-org** [comment]
We had updated the core to newer platform files.

In theory you could use this guide: https://github.com/qwertycoin-org/qwertycoin#android-building-on-linux for building this on ARM architecture.
