### ISSUE TITLE
Unintended Change

### ISSUE THREAD

**Issue by exploshot** [qwertycoin-org/qwertycoin#43]
@qwertycoin-org This change was not intended. Please, open an issue and assign it to me. I'll fix it in a separate PR after this one is merged.

_Originally posted by @speqtr in https://github.com/qwertycoin-org/qwertycoin/pull/42#issuecomment-475989048_

**Comment by speqtr** [comment]
I will fix this one tomorrow and open a new PR.

**Comment by speqtr** [comment]
This issue can be closed once PR https://github.com/qwertycoin-org/qwertycoin/pull/45 is merged.

**Comment by Qwertycoin** [comment]
See 78d00530d6578a3cf9a424a1514cfd6f994cb0c6
