### ISSUE TITLE
Where are the executables

### ISSUE THREAD

**Issue by nnpanda** [qwertycoin-org/qwertycoin#44]
Hi @speqtr 

maybe i forgot something but, where are the executables in the build directory?
qwertycoind.exe
miner.exe
walletd.exe
simplewallet.exe
connectivity_tool.exe

i can't find it in my build folder. But maybe it's only a outdated Readme.md

cmake -DBUILD_ALL:BOOL=TRUE ..
Or do you prefer other variant?

@qwertycoin-org This PR can be merge once you see that all CI scripts are "green" 🙂

_Originally posted by @speqtr in https://github.com/qwertycoin-org/qwertycoin/pull/42#issuecomment-475987634_

**Comment by Qwertycoin** [comment]
See last commit a7729bf695635d4aa02ba0227ad39c1d0752c4f2

**Comment by speqtr** [comment]
Hi @nnpanda,

Latest commit divides project into three big parts:
- sources in `lib` dir are always compiled;
- sources in `src` dir are build when `BUILD_WITH_TOOLS` is set to true;
- sources in `tests` dir are build when `BUILD_WITH_TESTS` is set to true;

Setting `DEVELOPER_BUILD` or `BUILD_ALL` option to true will enable all three targets, so running `cmake -DBUILD_ALL:BOOL=TRUE ..` should result in executables in build folder. In my case executables are placed in `qwertycoin/build/release/src`.

**Comment by speqtr** [comment]
@nnpanda @qwertycoin-org can we close this issue? Or is any additional information still required?

**Comment by Qwertycoin** [comment]
@speqtr We can close this Ticket.
