### ISSUE TITLE
Linux Build Warning

### ISSUE THREAD

**Issue by Xecute0101** [qwertycoin-org/qwertycoin#47]
**https://travis-ci.org/qwertycoin-org/qwertycoin/jobs/512233076**

[  4%] Performing build step for 'sparsehash'
/home/travis/build/qwertycoin-org/qwertycoin/build/_ExternalProjects/Build/sparsehash/missing: line 52: aclocal-1.11: command not found

**WARNING: `aclocal-1.11' is missing on your system.  You should only need it if
         you modified `acinclude.m4' or `configure.ac'.  You might want
         to install the `Automake' and `Perl' packages.  Grab them from
         any GNU archive site.**

 cd . && /bin/bash /home/travis/build/qwertycoin-org/qwertycoin/build/_ExternalProjects/Build/sparsehash/missing --run automake-1.11 --gnu
/home/travis/build/qwertycoin-org/qwertycoin/build/_ExternalProjects/Build/sparsehash/missing: line 52: automake-1.11: command not found

**WARNING: `automake-1.11' is missing on your system.  You should only need it if
         you modified `Makefile.am', `acinclude.m4' or `configure.ac'.
         You might want to install the `Automake' and `Perl' packages.
         Grab them from any GNU archive site.**

aclocal.m4:16: warning: this file was generated for autoconf 2.68.
You have another version of autoconf.  It may work, but is not guaranteed to.

@speqtr Could you look into this as well?

**Comment by speqtr** [comment]
@qwertycoin-org This is just a warning, not an error. All it says is that "you need aclocal-1.11 package in case you want to modify sparsehash sources". And we don't need it because we are not going to modify sources of sparsehash, we just want to compile them 🙂
