### ISSUE TITLE
Build Error on Ubuntu 16.04 | Header deprecated | Hunter

### ISSUE THREAD

**Issue by nnpanda** [qwertycoin-org/qwertycoin#60]
### System Information

**Operating System**: Ubuntu
**OS Version**: 16.04.6 x64
**CPU Make, Model, & Speed**: Unknown 1 Core
**Amount of RAM**: 1 GB
**Hard Drive Size**: 25 GB

### Qwertycoin Build Information

**Version:** 5.1.4 (0278679ef1710aefee8df8f3a761ae7b1cd55bd1)
**Binary Source:** Latest Master
**If self compiled, please provide all the build commands you used**
```
mkdir build && cd build
cmake -DBUILD_ALL:BOOL=TRUE ..
cmake --build . --config Release
```

**If self compiled, please provide of your Qwertycoin CMake output at the default verbosity**:
```
[ 61%] Building CXX object lib/CMakeFiles/QwertycoinFramework_Rpc.dir/Rpc/RpcServer.cpp.o
In file included from /root/.hunter/_Base/7f1604b/0ec0fcc/ac3fe71/Install/include/boost/random/detail/integer_log2.hpp:19:0,
                 from /root/.hunter/_Base/7f1604b/0ec0fcc/ac3fe71/Install/include/boost/random/detail/large_arithmetic.hpp:19,
                 from /root/.hunter/_Base/7f1604b/0ec0fcc/ac3fe71/Install/include/boost/random/detail/const_mod.hpp:23,
                 from /root/.hunter/_Base/7f1604b/0ec0fcc/ac3fe71/Install/include/boost/random/detail/seed_impl.hpp:26,
                 from /root/.hunter/_Base/7f1604b/0ec0fcc/ac3fe71/Install/include/boost/random/mersenne_twister.hpp:30,
                 from /root/.hunter/_Base/7f1604b/0ec0fcc/ac3fe71/Install/include/boost/uuid/random_generator.hpp:17,
                 from /root/.hunter/_Base/7f1604b/0ec0fcc/ac3fe71/Install/include/boost/uuid/uuid_generators.hpp:17,
                 from /root/qwertycoin/lib/P2p/P2pNetworks.h:20,
                 from /root/qwertycoin/lib/P2p/NetNode.h:47,
                 from /root/qwertycoin/lib/Rpc/RpcServer.cpp:41:
/root/.hunter/_Base/7f1604b/0ec0fcc/ac3fe71/Install/include/boost/pending/integer_log2.hpp:7:89: note: #pragma message: This header is deprecated. Use <boost/integer/integer_log2.hpp> instead.
virtual memory exhausted: Cannot allocate memory
lib/CMakeFiles/QwertycoinFramework_Rpc.dir/build.make:101: recipe for target 'lib/CMakeFiles/QwertycoinFramework_Rpc.dir/Rpc/RpcServer.cpp.o' failed
make[2]: *** [lib/CMakeFiles/QwertycoinFramework_Rpc.dir/Rpc/RpcServer.cpp.o] Error 1
CMakeFiles/Makefile2:903: recipe for target 'lib/CMakeFiles/QwertycoinFramework_Rpc.dir/all' failed
make[1]: *** [lib/CMakeFiles/QwertycoinFramework_Rpc.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
root@qwertycoin-1:~/qwertycoin/build#

```

**Comment by speqtr** [comment]
Hi @nnpanda 

Please, note that `note: #pragma message: This header is deprecated. Use <boost/integer/integer_log2.hpp> instead.` is just a warning. It's not the reason of your compilation error. An it is already on my TODO list and will be fixed in one of the next PRs that I'm planning to open this week.

You should look into `virtual memory exhausted: Cannot allocate memory`. This is the reason your build failed. This issue typically occurs on Linux VMs when there is not enough swap or RAM for succesfully compiling the project.

For example, compiling Qt with less than 4 GB of RAM may often fail with the similar issue.

**Comment by Xecute0101** [comment]
I experienced same issue with low ram VM.

**Comment by speqtr** [comment]
Today I looked into warning `note: #pragma message: This header is deprecated. Use <boost/integer/integer_log2.hpp> instead.` and it looks like it is internal Boost problem. In `qwertycoin-org/qwertycoin` code base there is no include `integer_log2.hpp`. Probably updating to Boost v1.70.0 will fix the problem. I'll do more testing tomorrow.

**Comment by Qwertycoin** [comment]
Maybe we should specify a system request in the readme?
2 or 4 GB of RAM, 1 Core at least 30 GB Disk Space or something like that?

**Comment by exploshot** [comment]
I had no while compiling.

Fresh installed Ubuntu 16.04 x64 Desktop.

![2019-04-20 00_57_51-Qwerty Test - VMware Workstation 15 Player (Non-commercial use only)](https://user-images.githubusercontent.com/9617859/56447238-6dd35c80-6307-11e9-9ac7-d59c021d1c0d.png)
![2019-04-20 00_56_13-Virtual Machine Settings](https://user-images.githubusercontent.com/9617859/56447242-7035b680-6307-11e9-9918-475e318fa284.png)

**Comment by Xecute0101** [comment]
For Ubuntu 18.04.2 LTS
![1](https://user-images.githubusercontent.com/38364793/56449019-7780b280-634f-11e9-9dfd-3b506ec4c4dc.JPG)
