### ISSUE TITLE
Progress of "code style changes"

### ISSUE THREAD

**Issue by speqtr** [qwertycoin-org/qwertycoin#67]
**NOTE:** This issue is created in order to keep track of code style changes and code base cleanup that I'm working on. For more details, please, refer to one of the issue or PR links that are listed below.

**Libraries cleanup (`include` and `lib` folders):**
- cleanup in `include` folder (PR #92, merged);
- cleanup in `lib/BlockchainExplorer` (PR #65, merged);
- cleanup in `lib/Common` (PR #66, merged);
- cleanup in `lib/crypto` (not doing, it's third-party lib and should be moved outside `lib` dir);
- cleanup in `lib/CryptoNoteCore` (PR #94, merged);
- cleanup in `lib/CryptoNoteProtocol` (PR #68, merged);
- cleanup in `lib/Http` (PR #71, merged);
- cleanup in `lib/InProcessNode` (PR #69, merged);
- cleanup in `lib/JsonRpcServer` (PR #70, merged);
- cleanup in `lib/Logging` (PR #72, merged);
- cleanup in `lib/Mnemonics` (PR #73, merged);
- cleanup in `lib/NodeRpcProxy` (#74, merged);
- cleanup in `lib/P2p` (PR #77, merged);
- cleanup in `lib/PaymentGate` (PR #76, merged);
- cleanup in `lib/Platform` (PR #86, merged);
- cleanup in `lib/Rpc` (PR #80, merged);
- cleanup in `lib/Serialization` (PR #82, merged);
- cleanup in `lib/System` (PR #83, merged);
- cleanup in `lib/Transfers` (PR #85, merged);
- cleanup in `lib/Wallet` (PR #88, merged);
- cleanup in `lib/WalletLegacy` (PR #91, merged).

**Sources cleanup (`src` folder)**
- cleanup in `config` (PR #93, merged);
- cleanup in `ConnectivityTool` (PR #93, merged);
- cleanup in `Daemon` (PR #93, merged);
- cleanup in `Miner` (PR #93, merged);
- cleanup in `PaymentGateService` (PR #93, merged);
- cleanup in `SimpleWallet` (PR #93, merged);

**Regressions (that will be fixed in the subsequent PRs):**
- _[fixed]_ changes in `StringBuffer` or `StringView` classes breaks two UnitTests;
- _[fixed]_ changes in `lib/BlockchainExplorer` breaks `BlockchainExplorerTests.getPoolStateEmpty`; and `BlockchainExplorerTests.getPoolStateMany`;
- _[fixed]_ changes in PR #75 broke test `TransactionValidation.gen_tx_check_input_unlock_time`, test data was updated to match new logic (PR #84);
- _[fixed]_ fixed regressions in `lib/P2p` that broke test `UnitTests.peer_list.peer_list_general` (PR #84);

**Comment by speqtr** [comment]
**NOTE:** I'll close this issue once all code style related changes will be done.

**Comment by speqtr** [comment]
This one was huge, but it is finally completed and can be closed 🎉 🍾 🤘

**Comment by speqtr** [comment]
@nnian please, close this issue 🙂

**Comment by nnian** [comment]
Sure i will wait until travis is done with it. https://travis-ci.org/qwertycoin-org/qwertycoin
