### ISSUE TITLE
Zero fee due to implicit type conversion

### ISSUE THREAD

**Issue by speqtr** [qwertycoin-org/qwertycoin#79]
In [this commit](https://github.com/qwertycoin-org/qwertycoin/commit/e18ea3a38ff22172d2346f68daaa13042ff86dfe) value of `REMOTE_NODE_FEE_FACTOR` was changed to `0.25`. Type of this variable is `uint64_t`. So value of this variable will be implicitly changed to `0`.

**Comment by speqtr** [comment]
Possible solution is to change `REMOTE_NODE_FEE_FACTOR` type from `uint64_t` to `double`.

**Comment by speqtr** [comment]
@nnian @Xecute0101 please, take a look at this bug.

**Comment by nnian** [comment]
Oh no, damned yes.
Integer for a decimal point *facepalm* 

Thanks =)

**Comment by nnian** [comment]
I will merge your PR and fix my PR asap when i'm home at my pc.

**Comment by speqtr** [comment]
Thanks 👍
