### ISSUE TITLE
EPoSe Movement #2 - Proposing Changes in Mixin

### ISSUE THREAD

**Issue by Xecute0101** [qwertycoin-org/qwertycoin#95]
Prerequisite: DB Implementation

Instead of utilizing ring confidential transaction (hiding information),

We should think about using statistics to make it more difficult to trace and pinpoint txs.

![1](https://user-images.githubusercontent.com/38364793/59545233-b2215880-8f56-11e9-9371-5c0b3cd3b3f9.PNG)

Here we see the pretty amounts for making outputs. From our blockchain history, the chain can analyze the population of each output in each digit space (statistical term). If conventional mixin focuses on mixing sudo and real inputs to obfuscate real outputs. What I am suggesting is to populate certain outputs so that their population grows over time and tracing txs more difficult because they all look the same or alike.

![2](https://user-images.githubusercontent.com/38364793/59545277-48557e80-8f57-11e9-804a-9f47b2490a64.PNG)

When high mixin is selected, outputs with most population in each digit is used to create txs and vice versa.

Any thoughts, guys?

**Comment by Xecute0101** [comment]
Like Where is Wally?

**Comment by exploshot** [comment]
I don't know if that would be to much but what's about analyzing the data from the past and create the outputs by AI, just as an idea.

**Comment by Xecute0101** [comment]
This change is based on individual chain's historical data. Adaptive approach.

**Comment by Xecute0101** [comment]
DB on our block data is required to proceed further.

**Comment by Xecute0101** [comment]
Thanks for taking our idea again Turtlecoin. Please work on your originality.

**Comment by Xecute0101** [comment]
Will reopen this issue if necessary.
