### ISSUE TITLE
[QIP] Improve application constants management

### ISSUE THREAD

**Issue by speqtr** [qwertycoin-org/qwertycoin#96]
###### QIP - Qwertycoin Improvement Proposal

**Summary**
Improve application constants management.

**Motivation**
- Using global variables is problematic, and it is common wisdom to avoid them unless they're absolutely necessary. Helpful comments can be found [here](https://stackoverflow.com/questions/484635/are-global-variables-bad);
- Global variables with static storage duration in many cases lead to "undefined behavior" and exceptions thrown by this variables can't be caught;
- Global definitations (like `#define VARIABLE_NAME VALUE`) can accidentally override variables from third-party modules, this will also result in "undefined behavior".

**Solution**
Create a single entry point (new `Constants` module) that will replace all currently existing:
- global variables (`#define VARIABLE_NAME VALUE`);
- settings (variables with static storage duration);
- `#undef ERROR` (this things in code look bad and extremely hack-ish);
- other const data.

In addition to all of the above, this new module will also help us to:
- remove relative imports like `#include "../src/config/header.h"`;
- simplify process of enabling disabling custom features at compile- and runtime.

**Comment by speqtr** [comment]
@nnian @Xecute0101 please, review and post your feedback 🙂

**Comment by nnian** [comment]
By now you know the code base better than we do. Do we have a large number of global variables (apart from those that are now in the config folder)?
(The motivation behind the /config folder was to simplify possible forks of the repository)

**Comment by speqtr** [comment]
I do think that `config` folder is one of the things that can be merged/moved into new `Constants` module. This way it will be possible to remove all relative paths like `#include "../src/config/header.h"` with proper absolute paths like `#include <Constants/config/header.h>`. Also it will make it easier to manage all of those settings.

**Comment by speqtr** [comment]
Also we have approximately 50 other variables declared as `#define VAR VALUE`.

**Comment by speqtr** [comment]
And we have many more variables with static storage duration that are mostly used to configure arguments parsing options for executables in `qwertycoin` project.

**Comment by speqtr** [comment]
All possible forks of this repositry will benefit from this, since they will be able to inherit from classes in new `Constants` module, easily overwrite one, two or more `constexpr` methods with their custom values and set this new custom config as default for their app.

**Comment by nnian** [comment]
Yes I understand. Basically, I think the idea is good, but @Xecute0101 manages the finances. I see some advantages and a few disadvantages. I do not know what Xecute is currently planning, let's wait until he answers.

btw
**Offtopic**: (Distributing the qwertycoind daemon across multiple processes / cores may be a good feature for load balancing for the SEED nodes in the future.) Sometime, the daemon is 100% busy because it uses only a single process. Maybe we could discuss this in a separate issue in the future.

**Comment by speqtr** [comment]
@nnian What disadvantages do you see in this solution? Maybe we can discuss them and find a solution?

> btw
Offtopic: (Distributing the qwertycoind daemon across multiple processes / cores may be a good feature for load balancing for the SEED nodes in the future.) Sometimes, the daemon is 100% busy because it uses only a single process. Maybe we could discuss this in a separate issue in the future.

Enabling multithreading support is a great feature and it will have a positive affect on daemon performance. But at the same time it may require significant changes to project architecture.

PS: Looking forward to @Xecute0101 comments 🙂

**Comment by Xecute0101** [comment]
Thank you for this proposal. To my knowledge, overall, this is a good practice it seems.
However, we need to focus on adding features related to blockchain at the moment.
Let's keep this issue open and work on it when we can.

**Comment by speqtr** [comment]
@Xecute0101 thank you for your feedback. Let's focus on blockchain related features then 🙂

**Comment by Xecute0101** [comment]
Let's move on with this proposal. @speqtr

**Comment by speqtr** [comment]
@Xecute0101 OK, tomorrow I'll start working on it.

**Comment by Xecute0101** [comment]
Ready to PR?

**Comment by speqtr** [comment]
@Xecute0101 PR is 99% ready. Doing final local code review and pushing it to GitHub later today.

**Comment by speqtr** [comment]
Further updates will be posted in PR #111.

**Comment by nnian** [comment]
I think we can finally close this PR after some patches in https://github.com/qwertycoin-org/qwertycoin/pull/120
